name: Run Storage retry conformance tests against service emulator

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/google-cloud-dotnet/google-cloud-dotnet/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.RetryConformanceTests/

    services:
      emulator:
        image: gcr.io/cloud-devrel-public-resources/storage-testbench:latest
        ports:
          - 9000:9000

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Install .NET Core 3.1 for testing
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      # Install .NET 6 for building
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.100

      - run: dotnet test Google.Cloud.Storage.V1.RetryConformanceTests.csproj
        env:
          TEST_BENCH_URL: http://localhost:9000/
          GOOGLE_APPLICATION_CREDENTIALS: C:/Users/anshuldavid/Desktop/GithubRepos/google-cloud-dotnet/conformance-tests/storage/v1/test_service_account.not-a-test.json
